def tab_mgr(tablenames):
    body = ""
    for tabname in tablenames:
        body += "public static %(titlename)s %(name)s { get; private set; }\n        " % {'name': tabname, 'titlename': tabname}

    staticbody = ""
    for tabname in tablenames:
        staticbody += "             %(name)s = new %(titlename)s();\n" % {'name': tabname, 'titlename': tabname}
    return "// Generated by tools.  DO NOT EDIT!\n\
// you can change template description in template_csharp.py\n\
namespace Table\n\
{\n\
    public static class TabMgr\n\
    {\n\
        %s\n\
\n\
        static TabMgr()\n\
        {\n\
%s\n\
        }\n\
    }\n\
}"% (body, staticbody)


def tab_body(body):
    return "// Generated by tools.  DO NOT EDIT!\n\
// you can change template description in template_csharp.py\n\
\n\
using System.Collections.Generic;\n\
using System.Linq;\n\
\n\
namespace Table\n\
{\n\
    %s\n\
}\n" % (body)

def tab_class(tablenames):
    body = ""
    for tabname in tablenames:
        body += "\n\
    public class %(name)s\n\
    {\n\
        public Pb.%(name)sStruct GetDataByID(int id)\n\
        {\n\
            if (!TryLoadFile()) { return null; }\n\
    \n\
            data.%(name)sStruct.TryGetValue(id, out Pb.%(name)sStruct value);\n\
            return value;\n\
        }\n\
    \n\
        public int Count { get { return data.%(name)sStruct.Count; } }\n\
    \n\
        public List<Pb.%(name)sStruct> GetDataList()\n\
        {\n\
            if (!TryLoadFile()) { return null; }\n\
    \n\
            if (m_dataList != null)\n\
                return m_dataList;\n\
    \n\
            m_dataList = data.%(name)sStruct.Select(v => v.Value).ToList();\n\
            return m_dataList;\n\
        }\n\
    \n\
        bool TryLoadFile()\n\
        {\n\
            if (data != null)\n\
                return true;\n\
            string tablePath = string.Format(TabHelper.TablePath, GetType().Name);\n\
            using (var input = System.IO.File.OpenRead(tablePath))\n\
            {\n\
                data = Pb.%(titlename)s.Parser.ParseFrom(input);\n\
            }\n\
    \n\
            if (data == null)\n\
                throw new System.Exception(\"Table Load file failed:\" + GetType().Name);\n\
    \n\
            return true;\n\
        }\n\
    \n\
        Pb.%(titlename)s data = null;\n\
        List<Pb.%(name)sStruct> m_dataList = null;\n\
    }\n\
    \n\
" % {'name' : tabname, 'titlename': tabname.title() }

    return tab_body(body)
